CREATE OR REPLACE STORAGE INTEGRATION
    DYNAMODB_SNOWFLAKE_BLOG
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = S3
    ENABLED = TRUE
    STORAGE_ALLOWED_LOCATIONS = ('s3://your-bucket-name/')
    STORAGE_AWS_ROLE_ARN = 'snowflake-access-role-arn';