version: "3.0"

services:
    ddbimport:
        image: adrianhesketh/ddbimport
        command:  
            - /dataload/container-load-data-files.sh
        volumes:
            - ./:/dataload
        environment:
            - INPUTDATADIR
            - DYNAMODB_TABLE_NAME
            - AWS_DEFAULT_REGION
            - AWS_SESSION_TOKEN
            - AWS_SECRET_ACCESS_KEY
            - AWS_ACCESS_KEY_ID
